Improvements in the configure step for r2api integration

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,7 +19,7 @@ control_c() {
 }
 trap control_c 2
 HAVE_FORK=1
-USE_R2=0
+WANT_R2=0
 split_host() {
 S="$"
 while : ; do
@@ -192,6 +192,7 @@ case $flag in
 -r|--r|--report)
 echo "PKGNAME:   spp"
 echo "VERSION:   1.1.0"
+echo "PKG-CONFIG:  r_util"
 echo "FLAGS:     --without-fork --enable-r2"
 	exit 0
 	;;
@@ -239,7 +240,7 @@ echo "FLAGS:     --without-fork --enable-r2"
 	MANDIR="$value"; ;;
 
 "--without-fork") HAVE_FORK="0"; ;;
-"--enable-r2") USE_R2="1"; ;;
+"--enable-r2") WANT_R2="1"; ;;
 *) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
@@ -257,7 +258,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL HAVE_FORK USE_R2"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL HAVE_FORK WANT_R2 HAVE_PKGCONFIG PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_UTIL USE_R2"
 
 create_environ
 
@@ -272,6 +273,48 @@ echo "checking for working directories... ${WODIS}"
 echo "using prefix '${PREFIX}'"
 ACR_RMFILES=""
 
+
+printf "checking for pkg-config... "
+if [ -x "${PKGCONFIG}" ]; then
+	FIND=${PKGCONFIG}
+else
+	FIND=""
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/pkg-config" ]; then
+			FIND="${A}/pkg-config"
+			break;
+		fi
+	done
+	unset IFS
+fi
+if [ -n "${FIND}" ]; then
+	echo ${FIND};
+HAVE_PKGCONFIG=1
+	PKGCONFIG=${FIND}
+else
+	HAVE_PKGCONFIG=0
+	PKGCONFIG=pkg-config
+echo no ; fi
+[ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
+echo 'Using PKGCONFIG: '${PKGCONFIG}
+printf 'checking pkg-config flags for r_util... '
+tmp=`${PKGCONFIG} --cflags r_util 2>/dev/null`
+if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_R_UTIL=0;
+R2_CFLAGS='';R2_LDFLAGS='';
+else
+R2_CFLAGS=$tmp;
+tmp=`${PKGCONFIG} --libs r_util 2>/dev/null`
+if [ $? = 0 ]; then
+echo yes; HAVE_PKGCFG_R_UTIL=1;
+R2_LDFLAGS=$tmp; fi; fi
+USE_R2="0"
+if [ "$WANT_R2" = "1" ]; then
+if [ ! "$R2_CFLAGS" = "" ]; then
+USE_R2="1"
+else
+case "$undefined_variable" in 0|"") echo ; echo "ERROR: Cannot find -lr_util using pkg-config" >&2 ; echo ; exit 1 ;; esac; fi; fi
 SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
